### PR TITLE
Changed detecting of the highest PermissionGroup

### PR DESCRIPTION
**Pull request by juliarn**
Currently the highestGroup is being detected via the joinPower. I changed it to be detected by the lowest tagId, so the visualisation of the strongest group matches with the internal strongest group of a player.

Because of this adjustment, I also changed the PermissionProvider to still return the same result as before when getting a players' joinPower.

### CODE REVIEW

**Comment by derklaro** [comment]
Are you sure that is a good idea? I mean, for example i have a permission group which should be higher in the tab but is not the highest group... Got it?

**Comment by juliarn** [comment]
Correct, but same issue with the joinPower. I think that the joinPower is something feature-specific but the tagId sorts the groups. So it's the better solution in my opinion.

**Comment by GiantTreeLP** [comment]
Given that the join power has been patched to be calculated correctly, this is fine.

The highest permission group is often thought of to be the one with the lowest tag id.
Though I would recommend rewriting the getHighestPermissionGroup method.

**Comment by juliarn** [comment]
I first planned to rewrite it, but then thought changing the least possible would be the best. Ok, I'll do that now.

**Comment by juliarn** [comment]
This should be it

**Pull request merged**
