### PR TITLE
Use ExecutorService for the local wrappers console

### PR DESCRIPTION
**Pull request by einrobin**
Use an ExecutorService to read the console and wait for the console output to not waste resources

### CODE REVIEW

**Comment by GiantTreeLP** [comment]
Have you tested this and the cpu usage?

**Comment by einrobin** [comment]
It works and the cpu usage of the master is around 0 - 1 %

**Comment by TheMeinerLP** [comment]
@McRuben Check out the code from me is more performant as your code to read the console
https://github.com/CloudNetService/CloudNet/blob/master/cloudnet-cord/cloudnet-setup/src/main/java/de/dytanic/cloudnet/setup/utils/StreamThread.java

**Comment by GiantTreeLP** [comment]
@McRuben just use the code from @MeinerLP1 and adapt it for System.err

**Comment by einrobin** [comment]
I need the whole lines and not only some chars (for printing "LocalWrapper | " at the start of every line), so why shouldn't we use this reader?

**Comment by GiantTreeLP** [comment]
I forgot that, use the reader (if you like, use a buffered reader).

**Comment by GiantTreeLP** [comment]
Is this done and tested?

**Comment by einrobin** [comment]
Yes, it works fine

**Pull request merged**
