### PR TITLE
Fixed NullPointerException in the SignSelector if a server is added, …

### PR DESCRIPTION
**Pull request by einrobin**
…online and not ingame

### CODE REVIEW

**Comment by GiantTreeLP** [comment]
Have you tested this?
If you have, let me know, so I can merge this.

**Comment by einrobin** [comment]
No, but it was in the else block where the "sign" is always null and "newSign" not and I don't know how to reproduce this without a normal startup of a server.

**Comment by GiantTreeLP** [comment]
So what does this change do?

**Comment by einrobin** [comment]
It fixes the NullPointerException when a new Server was started and is in the ingame mode.

**Comment by GiantTreeLP** [comment]
I don't see it breaking anything.
Merging.

**Pull request merged**
