### PR TITLE
Add tab completion - Update for 2.1.16

### PR DESCRIPTION
**Pull request by TheMeinerLP**

### CODE REVIEW

**Comment by GiantTreeLP** [comment]
This needs to be rebased and the functional Java commit needs to be removed.

**Comment by GiantTreeLP** [comment]
As I wrote before, please remove commits that are part of another pull request.
Adding tab completion shouldn't be any more than changes to 2 files.

**Comment by TheMeinerLP** [comment]
Same a other PR. How i can do that ?

**Comment by TheMeinerLP** [comment]
But the master and wrapper support the tab completion not right!

**Comment by TheMeinerLP** [comment]
Think this pull request is ready to merge into development branch. Please review the code @GiantTreeLP

**Comment by GiantTreeLP** [comment]
Tabcomplete for /cloud does not work at all.
The command itself is not present in the command list and tabbing for autocomplete does not work.

**Comment by TheMeinerLP** [comment]
Now is the finally version. Please review!
@GiantTreeLP 
@byRoadrunner

**Pull request merged**
