### PR TITLE
Remove fast connect

### PR DESCRIPTION
**Pull request by juliarn**
CloudNet currently has an option called "fast-connect", which doesn't really work.
There are often chunk-bugs, players are invisible etc.
CloudNet does this in way which should be avoided, according to wiki.vg: https://imgur.com/vbOUWhT
In addition, fast connect is not a feature which is necessary in a server-management system.

### CODE REVIEW

**Comment by GiantTreeLP** [comment]
I share your opinion, but I think we should not make this change without community involvement.

**Comment by juliarn** [comment]
Well, I don't think it's working properly 🤷‍♂ 
But yes, making a suggestion before removing it might be the better way.

**Comment by GiantTreeLP** [comment]
Oh, by the way: I don't know, if you can make it, but it would be nice, if the config option would be removed as well.

**Comment by juliarn** [comment]
Should I keep the getter and just make it return false?

**Comment by GiantTreeLP** [comment]
Does this code work when updating from a version that still has fast-connect in its configuration?

So far, 12 upvotes suggest to me, that this change can be merged, once testing has been completed successfully.

**Comment by juliarn** [comment]
Haven't tested it, but I don't think that there will be issues. I can test it later.

**Comment by GiantTreeLP** [comment]
The test is very important. If the config becomes invalid due to the extraneous "fast-connect" field, it can reset or crash the entire master.

**Comment by juliarn** [comment]
Yeah, that's a thing that should be fixed too

**Comment by juliarn** [comment]
No errors when starting the Master, as expected.

**Comment by GiantTreeLP** [comment]
Great

**Pull request merged**
