### PR TITLE
Remove ssl option

### PR DESCRIPTION
**Pull request by TheMeinerLP**

### CODE REVIEW

**Comment by Sarsum** [comment]
What is the point of removing the SSL option????

**Comment by GiantTreeLP** [comment]
> What is the point of removing the SSL option????

It doesn't work. That's the point

**Comment by derklaro** [comment]
You can add an option to use own ssl certificates. Thats much better than removing it completely.

**Comment by GiantTreeLP** [comment]
> You can add an option to use own ssl certificates. Thats much better than removing it completely.

That would require an entire rewrite of the WebServer component, feel free to post it ;)

**Comment by derklaro** [comment]
You can create a sslcontext using a cert and key file :smart:

**Comment by GiantTreeLP** [comment]
Doesn't do much, when you need a keyStore and an SslHandler to validate the certificate.

**Comment by TheMeinerLP** [comment]
Have found a better way to integrated a full ssl support

**Pull request closed without merging**
