### PR TITLE
Bugfix/#186

### LINKED ISSUE #186: Fix loading templates
https://github.com/CloudNetService/CloudNet/blob/cb3f7a126ae76374fcb18b04273705f3565ade7f/cloudnet-wrapper/src/main/java/de/dytanic/cloudnetwrapper/server/GameServer.java#L276-L282

@MeinerLP1 please fix this asap, due to the nature of `&`, this is not short-circuiting.

Also, `STATIC_LOBBY` servers are not handled.

### PR DESCRIPTION
**Pull request by TheMeinerLP**
Try to fix #186

### CODE REVIEW

**Comment by TheMeinerLP** [comment]
Is in testing on my ci

**Comment by GiantTreeLP** [comment]
Fix has been tested working.

@MeinerLP1 is this PR ready and tested on your end?

**Comment by TheMeinerLP** [comment]
Is tested and on the end. Some other changes like rework coming in the future in extra pr

**Comment by TheMeinerLP** [comment]
@GiantTreeLP

**Pull request merged**
