### PR TITLE
WIP: Changed bracket position to follow the code conventions of java

### PR DESCRIPTION
**Pull request by derklaro**

### CODE REVIEW

**Comment by juliarn** [comment]
Why did you remove the @Deprecated from getPlayerAndCache? And just changing the name of a public method might break software of users that use the api.

**Comment by juliarn** [comment]
It's better to deprecate the method and create a new one

**Comment by derklaro** [comment]
HUH
Where?

**Comment by derklaro** [comment]
I think it was in an older commit or intelji removed it 🤷‍♂️

**Comment by juliarn** [comment]
You removed the deprecated in 614e244 and nvm about the method-name change, it's just an event handler

**Comment by juliarn** [comment]
But I think calling all eventhandlers "handle" is not very good. The method name should describe what happens

**Comment by derklaro** [comment]
Yes, that was an older commit, i gonna remove that

**Comment by derklaro** [comment]
It's already removed, the string util method, too

**Comment by juliarn** [comment]
614e244 is still there

**Comment by derklaro** [comment]
Yes, but overridden by the other commit (https://github.com/KlaroYT/CloudNet/blob/development/cloudnet-api/cloudnet-api-bridge/src/main/java/de/dytanic/cloudnet/bridge/internal/listener/bukkit/BukkitListener.java)

**Comment by juliarn** [comment]
But I Think it will be not very easy to accept this PR anyway. All other open PRs can't be merged because your commits affect every class of the cloud.

**Comment by GiantTreeLP** [comment]
> But I Think it will be not very easy to accept this PR anyway. All other open PRs can't be merged because your commits affect every class of the cloud.

No problem, we can manually merge anyways

**Comment by juliarn** [comment]
Yes, but I dont think Tarek will like this PR xD

**Comment by derklaro** [comment]
Yes but a good source can rescue lifes :smart:

**Comment by GiantTreeLP** [comment]
Given that this is just a style change, this looks good to me.

I would delay the merge until 2.1.15 has been merged though.

**Comment by GiantTreeLP** [comment]
I'm pretty sure this PR needs to be redone once the 2.1.16 changes have been merged and other changes have been added.
This PR should then be first priority and no other PR should be merged until this one has been merged.

**Pull request closed without merging**
